spring.application.name: fpp

spring.kafka.properties.sasl.mechanism: PLAIN
spring.kafka.properties.bootstrap.servers: pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='RPJXOK3O3ONHZ64Y' password='pJds8EAHUSrMXMp/HawHGDMGZtde7XcUbcKaEs1gcWKJDUAY+8zsptc+mE3ErdBO';
spring.kafka.properties.security.protocol: SASL_SSL

# Confluent Cloud Schema Registry configuration
spring.kafka.properties.basic.auth.credentials.source: USER_INFO
spring.kafka.properties.schema.registry.basic.auth.user.info: RPJXOK3O3ONHZ64Y:pJds8EAHUSrMXMp/HawHGDMGZtde7XcUbcKaEs1gcWKJDUAY+8zsptc+mE3ErdBO
spring.kafka.properties.schema.registry.url: https://psrc-4j8q8.europe-west3.gcp.confluent.cloud

#spring.cloud.function.definition: referenceFPSSortCodesSupplier1;referenceFPSSortCodesSupplier2;referenceFPSSortCodesSupplier3;referenceFPSSortCodesSupplier4;referenceFPSSortCodesSupplier5;referenceFPSSortCodesSupplier6;referenceFPSSortCodesSupplier7;referenceFPSSortCodesSupplier8;fpsPaymentSupplier
spring.cloud.function.definition: referenceFPSSortCodesSupplier1;fpsPaymentSupplier;fpsPaymentInboundSupplier;fpsPaymentOutboundSupplier

spring.cloud.stream.bindings.referenceFPSSortCodesSupplier1-out-0.destination: reference-fps-sort-codes-1
spring.cloud.stream.kafka.bindings.referenceFPSSortCodesSupplier1-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.bindings.referenceFPSSortCodesSupplier2-out-0.destination: reference-fps-sort-codes-2
spring.cloud.stream.kafka.bindings.referenceFPSSortCodesSupplier2-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.bindings.fpsPaymentSupplier-out-0.destination: fps-payment
spring.cloud.stream.kafka.bindings.fpsPaymentSupplier-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.bindings.fpsPaymentInboundSupplier-out-0.destination: fps-payment-inbound
spring.cloud.stream.kafka.bindings.fpsPaymentInboundSupplier-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.bindings.fpsPaymentOutboundSupplier-out-0.destination: fps-payment-outbound
spring.cloud.stream.kafka.bindings.fpsPaymentOutboundSupplier-out-0.producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer

spring.output.ansi.enabled: ALWAYS

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

management.endpoints.web.exposure.include: "*"